### PR TITLE
Fix: Make background color fill whole page

### PR DESCRIPTION
**Pull request by ZhichGaming**
This much CSS in globals.css is fine right...?

### CODE REVIEW

**Review by Ch3ru09 — COMMENTED** [review]
I fixed that in a previous commit, look into the root layout (app/layout)
The body already has a bg-color

**Comment by ZhichGaming** [comment]
I do not see a background color in app/layout.tsx: 

```
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InfoContextProvider>{children}</InfoContextProvider>
      </body>
    </html>
  );
}
```

We are running into the issue of the background color cutting off if the content has to be scrolled. That currently happens for me on the home screen and the emails overflowing on the email screen.

**Comment by Ch3ru09** [comment]
Can you pull from Ch3ru main

**Comment by ZhichGaming** [comment]
This is the result from upstream/main. The color does not extend. 

image

**Comment by Ch3ru09** [comment]
Can you send a picture of your app/layout.tsx

**Comment by ZhichGaming** [comment]
The code of the screenshot is attached to my previous comment. However, I see now that layout.tsx has changed with some new commits but I am running into this error which prevents me from viewing the results of this UI: 

```
./src/app/(home)/_components/layout/ToolBar.module.css
Error: Cannot find module 'tailwindcss-animate'
Require stack:
- /Users/sony0627/Programming/student-website/tailwind.config.js
```

**Comment by Ch3ru09** [comment]
Try reinstalling tailwind ```npm i -D tailwindcss```

**Comment by Ch3ru09** [comment]
Nope, nevermind, ik what the problem is

**Comment by Ch3ru09** [comment]
I installed a UI library...

**Comment by ZhichGaming** [comment]
lmao

**Comment by Ch3ru09** [comment]
I reverted main, try to see if it works better

**Comment by ZhichGaming** [comment]
Nice, everything works nicely now and background color applies to the whole page. Apologies for the disturbance, good night!

**Pull request closed without merging**
